# Generated by Django 5.1.7 on 2025-03-31 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_sentiment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_weight', models.IntegerField(default=33, help_text='Percentage weight for positive articles (0-100)')),
                ('negative_weight', models.IntegerField(default=33, help_text='Percentage weight for negative articles (0-100)')),
                ('neutral_weight', models.IntegerField(default=34, help_text='Percentage weight for neutral articles (0-100)')),
                ('last_sentiment_filter', models.CharField(choices=[('all', 'All'), ('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excluded_categories', models.ManyToManyField(blank=True, related_name='excluded_by', to='core.category')),
                ('excluded_sources', models.ManyToManyField(blank=True, related_name='excluded_by', to='core.source')),
                ('favorite_categories', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.category')),
                ('favorite_sources', models.ManyToManyField(blank=True, related_name='favorited_by', to='core.source')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
