# Generated by Django 5.1.7 on 2025-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='The keyword or phrase to match', max_length=100, unique=True)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='The sentiment to assign', max_length=10)),
                ('priority', models.IntegerField(default=1, help_text='Higher priority keywords take precedence (1-10)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive keywords are not used in analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'keyword'],
                'indexes': [models.Index(fields=['sentiment', 'is_active'], name='feed_fetche_sentime_006ac2_idx')],
            },
        ),
    ]
